name: Build webOS IPK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install working webOS CLI
      run: |
        npm install -g npm@9
        npm install -g @webos-tools/cli@2.4.0

    - name: Package App
      run: ares-package .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webos-package
        path: |
          *.ipk
