name: Generar IPK de Clasicofilm TV

on:
  workflow_dispatch: # Nos permite pulsar el botón para compilar cuando queramos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js (Versión Moderna 24)
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Instalar herramientas CLI de LG webOS
      run: npm install -g @webos-tools/cli

    - name: Empaquetar la aplicación (.ipk)
      run: ares-package .

    - name: Guardar el archivo .ipk generado
      uses: actions/upload-artifact@v4
      with:
        name: Clasicofilm-TV-Instalador
        path: "*.ipk"
